[package]
name = "trellis-genesis"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Genesis crate, initializes the system when first deployed."

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
trellis-core = { workspace = true }
thiserror = "2.0.20"

[lints]
workspace = true
